### ISSUE TITLE
move the "pop-out video" icon on videos

### ISSUE THREAD

**Issue by Gohan6** [ettoolong/PopupVideo#2]
The icon for "pop-out video" is on the top right of the videos.
It overlaps the "add to watch later" button on YouTube.

Move the icon to a different location
note: bottom right is the video length

ideally: allow the user to select where the icon will appear

**Comment by ettoolong** [comment]
Update version 0.0.4:
Add new option for overlay icon position. options: top-center, top-left and top-right.

Thanks for your feedback.
