### ISSUE TITLE
Request: Just one instance

### ISSUE THREAD

**Issue by TomberWolf** [ettoolong/PopupVideo#21]
Hey,

do you think it's possible to add an option to have just one instance?
So when we click on the popup button it should replace the previous one.

That would make it much more comfortable  to browse through video / Youtube clips, because we just don't need to close / mute the older popups firstly.

**Comment by ettoolong** [comment]
@TomberWolf, 
about:addons > Popup Video preferences > Uncheck **Allow popup multi video window**

**Comment by TomberWolf** [comment]
😁🤦‍♂️
Thanks
