### ISSUE TITLE
Option for specifying popup button location

### ISSUE THREAD

**Issue by mirkogrcic** [ettoolong/PopupVideo#22]
Hello, can you make an option to select where should the popup button be located (top/left,top/right,bottom/left,bottom/right) as it currently blocks the watch later button
Without the extension:
![image](https://user-images.githubusercontent.com/11380296/67163731-c517bf80-f372-11e9-855c-a840859b625d.png)

With the extension:
![image](https://user-images.githubusercontent.com/11380296/67163746-e4165180-f372-11e9-8849-cff6751d9a5b.png)

Fortunately I have the option to click the 3 dots button and then save for later but it's an inconvenience.
Thank you for the great extension, it works great.

**Comment by ettoolong** [comment]
@mirkogrcic,
about:addons > Popup Video preferences > Add popup video icon on video/thumbnail - Position
You can change to **Top left** or **Top center**

**Comment by mirkogrcic** [comment]
Thanks, I was there and did not see the preferences at the time, thanks.
