### ISSUE TITLE
Conex Compatibility

### ISSUE THREAD

**Issue by maverick74** [ettoolong/PopupVideo#6]
Does not work with Conex ( https://addons.mozilla.org/en-US/firefox/addon/conex/ )

When popup button is pressed it opens the window and closes it immediately. This started to happen when i activated the Conex addon!

**Comment by ettoolong** [comment]
Popup Video v0.0.6:
Please open Popup Video Preferences and find "Open popup window in private browsing" option, then enable it.

Thanks for your feedback.

**Comment by maverick74** [comment]
@ettoolong Working like a charm!! Thanks :)
