### ISSUE TITLE
Custom Window Size Option

### ISSUE THREAD

**Issue by Koastin** [ettoolong/PopupVideo#8]
Great work with this, just what i was looking for!  Thank you.

Noticed the feature to choose a custom window size is available in your other popup add-on...Is it possible to add it to this one?  Most videos i watch on YouTube are a bit narrower than the default size.

Also curious if it would be possible to have an option to automatically send an 'ctrl+space bar" command after the pop up windows opens to set it on top using the common auto hot key script?

**Comment by ettoolong** [comment]
Popup Video v0.0.6 support custom window size.
About auto hot key script, I don't know how to do that.

Thanks for your feedback.
