### ISSUE TITLE
Request from a NON Firefox Quantum user

### ISSUE THREAD

**Issue by LL25255252** [ettoolong/PopupVideo#9]
I decided not to upgrade to Firefox Quantum so I use the old https://addons.mozilla.org/en-US/firefox/addon/popup-video/ addon. It works great on the Firefox 52 ESR and on the Basilisk browser.
Still, there's one problem on youtube videos. The popup video icon hides youtube's "watch it later" icon.
Can you please release another version of the 'old" addon with an option to decide the icon location (top-right, top-center or top-left).
If not, can you instruct me how to change the code of the xpi (is it on the launch-video.js file ?) so the icon will be shown on the top-left of the thumbnail.
Thanks in advance.

Win 7 x64
Basilisk 2018.06.01 (32-bit)

**Comment by ettoolong** [comment]
Update version 0.0.9

**Comment by LL25255252** [comment]
First, thanks a lot @ettoolong for updating the Non Quantum version. I really appreciate it.
Just one problem. Version 0.0.9 suddenly removed the overlay icon for the thumbnails.
Win 7 x64
Basilisk 2018.06.01 (32-bit) & Firefox 52 ESR
